// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// `prisma generate` doit tourner sans DATABASE_URL (jobs CI lint/typecheck/build,
// stage Docker builder) : à ce moment-là on ne se connecte à aucune base. On évite
// donc `env("DATABASE_URL")`, qui lève si la variable est absente, avec un repli
// placeholder. Les environnements réels (local via .env, job `test` du CI, prod)
// fournissent la vraie URL, qui prime.
const databaseUrl =
  process.env.DATABASE_URL ??
  "postgresql://placeholder:placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    url: databaseUrl,
  },
});
